[workspace]
resolver = "3"
members = [
    "maxima-bootstrap",
    "maxima-cli",
    "maxima-lib",
    "maxima-service",
    "maxima-tui",
    "maxima-ui",
    "maxima-resources",
]

[workspace.dependencies]
# Common Workspace Dependencies for all Maxima libs
tokio = { version = "1.52.3", features = ["full", "rt", "rt-multi-thread", "time", "net"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
reqwest = { version = "0.13.4", features = ["stream", "rustls"], default-features = false }
base64 = "0.22.1"
thiserror = "2.0.18"
anyhow = "1.0.102"
lazy_static = "1.5.0"
log = "0.4.32"
regex = "1.12.4"
futures = "0.3.32"
clap = { version = "4.6.1", features = ["derive"] }
inquire = "0.9.4"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
url = "2.5.8"
querystring = "1.1.0"
directories = "6.0.0"
hex = "0.4.3"

# Common Target Specific Dependencies
winapi = { version = "0.3.9", features = ["memoryapi", "handleapi", "synchapi", "wincon", "consoleapi"] }
winreg = "0.56.0"
windows-service = "0.8.1"
is_elevated = "0.1.2"

[profile.release]
strip = true

[patch.crates-io]
flate2 = { git = 'https://github.com/sjp761/flate2-rs.git' }
async-compression = { git = 'https://github.com/sjp761/async-compression.git' }
