syntax = "proto3";
package eadp.rtm;

// incomplete, wip

message ConversationChannelV1 {
  string channel_id = 1;  // e.g. "<nucID1>-<nucID2>-CrossGame"
}

message ConversationHistoryRequestV1 {
  string channel_id = 1;
  string timestamp = 2;
  int32 limit = 3;
  string message_type = 4;  // "TEXT_MESSAGE"
}

message TypingEventV1 {
  string channel_id = 1;
  string timestamp = 2;
}

message PlayerContextV1 {
  PlayerRef player = 2;
  int32 unknown3 = 3;
}

message PlayerRef {
  string player_id = 1;
  string product_id = 2;  // "origin"
}
