syntax = "proto3";

import "config.proto";
import "player.proto";
import "presence.proto";
import "antelope_common.proto";

package antelope.rtm;

enum ChannelType {
  NO_CHANNEL_TYPE = 0;
  EADP_GROUP_SERVICE = 1;
  INVITE_CHANNEL = 2;
  WORLD_CHAT = 3;
  GAME = 4;
}

enum MutedByV1 {
  NO_MUTE = 0;
  ADMIN_MUTED = 1;
  USER_MUTED = 2;
}

enum ContentTypeValue {
  NO_CONTENT = 0;
  GIFT = 1;
  GAME_INVITE = 2;
  OTHER = 3;
}

enum MessageType {
  NO_MESSAGE = 0;
  REGULAR_MESSAGE = 1;
  STICKY_MESSAGE = 2;
  QUICK_MESSAGE = 3;
}

enum UserType {
  NONE_USERTYPE = 0;
  PERSONA = 1;
  NUCLEUS = 2;
}

message PersonaV1 {
  string personaId = 1;
  string displayName = 2;
  string nickName = 3;
}

message SuccessV1 {
  oneof body {
    LoginV2Success loginV2Success = 1;
    ChatInitiateSuccessV1 chatInitiateSuccess = 2;
    LoginV3Response loginV3Response = 3;
  }
}

message LoginV2Success {
  string sessionKey = 1;
}

message ChatInitiateSuccessV1 {
  ChannelV1 channel = 1;
}

message MutedSetV1 {
  repeated MutedByV1 mutedBy = 1;
}

message ChannelV1 {
  string channelId = 1;
  string channelName = 2;
  ChannelType type = 3;
  int32 unreadMessageCount = 4;
  TextMessageV1 lastMessageInfo = 5;
  string lastReadTimestamp = 6;
  string customProperties = 7;
  bool crossGame = 8;
}

message ChannelMuteListV1 {
  string channelId = 1;
  repeated PersonaV1 mutedUsers = 2;
  repeated MutedSetV1 mutedBy = 3;
  repeated Player mutedPlayers = 4;
}

message HeartbeatV1 {
}

message StickyMessageV1 {
  string stickyAuthorPersonaId = 1;
  string stickyAuthorDisplayName = 2;
  string timestamp = 3;
  TextMessageV1 textMessage = 4;
  string messageId = 5;
  string stickyAuthorNickName = 6;
  string stickyAuthorPlatformDisplayName = 7;
  string stickyAuthorPlatformNickName = 8;
}

message TextMessageV1 {
  string fromPersonaId = 1;
  string fromDisplayName = 2;
  string timestamp = 3;
  string text = 4;
  string originalText = 5;
  Player player = 6;
  string fromNickName = 7;
  string fromPlatformDisplayName = 8;
  string fromPlatformNickName = 9;
  string metadata = 10;
  MessageType messageType = 11;
  StringId textMessageId = 12;
  MessageContext messageContext = 13;
  repeated ChatPropertyBagEntry chatPropertyBag = 14;
}

message ChatPropertyBagEntry {
  string key = 1;
  ChatPropertyValue value = 2;
}

message ChatPropertyValue {
  oneof value {
    string stringValue = 1;
    int64 integerValue = 2;
    double floatValue = 3;
    ChatPropertyTimestamp chatPropertyTimestampValue = 4;
    ChatPropertyDuration chatPropertyDurationValue = 5;
  }
}

message ChatPropertyTimestamp {
  int64 seconds = 1;
  int32 nanos = 2;
}

message ChatPropertyDuration {
  int64 seconds = 1;
  int32 nanos = 2;
}

message MessageContext {
  .antelope.rtm.PlayerNetworkId senderPlayerNetworkId = 1;
  .antelope.rtm.DevicePlatformId senderDevicePlatformId = 2;
  .antelope.rtm.ProductId senderProductId = 3;
  .antelope.rtm.PlayerNetworkId receiverPlayerNetworkId = 4;
  .antelope.rtm.DevicePlatformId receiverDevicePlatformId = 5;
  ContentType contentType = 6;
}

message ContentType {
  oneof body {
    ContentTypeValue type = 1;
    string customContentType = 2;
  }
}

message LoginV3Response {
  string sessionKey = 1;
  repeated SessionV1 connectedSessions = 2;
}

message SessionV1 {
  string sessionKey = 1;
  PlatformV1 platform = 2;
  string clientVersion = 3;
  string timestamp = 4;
}

message SessionRequestV1 {
}

message SessionResponseV1 {
  repeated SessionV1 connectedSessions = 1;
}

message SessionCleanupV1 {
  string sessionKey = 1;
}

message StringId {
  string id = 1;
}