syntax = "proto3";

package com.ea.eadp.antelope.rtm.protocol;

enum ChannelMessageType {
  NO_CHANNEL_MESSAGE_TYPE = 0;
  TEXT_MESSAGE = 1;
  BINARY_MESSAGE = 2;
  GROUP_MEMBERSHIP_CHANGE = 3;
  CHAT_CONNECTED = 4;
  CHAT_DISCONNECTED = 5;
  CHAT_LEFT = 6;
  CUSTOM_MESSAGE = 7;
  CHAT_USER_MUTED = 8;
  CHAT_USER_UNMUTED = 9;
  CHANNEL_MEMBERSHIP_CHANGE = 10;
  STICKY_MESSAGE_CHANGED = 11;
  CHAT_TYPING_EVENT = 12;
  WORLD_CHAT_MEMBERSHIP_CHANGE = 13;
  GROUP_MEMBER_ATTRIBUTE_CHANGE = 14;
  GROUP_ATTRIBUTE_CHANGE = 15;
  GROUP_MEMBER_ROLE_CHANGE = 16;
}