syntax = "proto3";

package com.ea.eadp.antelope.rtm.protocol;

enum SessionNotificationTypeV1 {
  NOTHING = 0;
  DEFAULT = 1;
  FORCE_DISCONNECT = 2;
  USER_LOGGED_IN = 3;
  USER_LOGGED_OUT = 4;
  CHAT_CHANNEL_UPDATE = 5;
}

message NotificationV1 {
  string type = 1;
  string payload = 2;
}

message UserMembershipChangeV1 {
  ChannelMembershipChangeType type = 1;
  ChannelV1 channel = 2;
}

message SessionNotificationV1 {
  SessionNotificationTypeV1 type = 1;
  string message = 2;
  PlatformV1 platform = 3;
  int32 sessionLimitRemaining = 4;
  SessionV1 connectedSessions = 5;
  ChatChannelUpdateV1 chatChannelUpdate = 6;
}

message WorldChatNotificationV1 {
  string sessionKey = 1;
  string worldName = 2;
}