syntax = "proto3";

package com.ea.eadp.antelope.rtm.protocol;

enum BasicPresenceType {
  NONE_PRESENCE = 0;
  UNKNOWN_PRESENCE = 1;
  OFFLINE = 2;
  ONLINE = 3;
  DND = 4;
  AWAY = 5;
  INVISIBLE = 6;
  CUSTOM = 7;
}

enum RichPresenceType {
  NONE_RICH_PRESENCE = 0;
  UNKNOWN_RICH_PRESENCE = 1;
  LFG = 2;
  BROADCASTING = 3;
}

enum PlatformV1 {
  NONE_PLATFORM = 0;
  UNKNOWN_PLATFORM = 1;
  MOBILE = 2;
  PC = 3;
  WEB = 4;
  XBOXLIVE = 5;
  PSN = 6;
  SWITCH = 7;
  STEAM = 8;
  XBSK = 9;
  PS5 = 10;
}

message PresenceSubscribeV1 {
  repeated string personaId = 1;
  repeated Player players = 2;
}

message PresenceSubscribeAllFriendsV1 {
}

message PresenceUnsubscribeV1 {
  repeated string personaId = 1;
  repeated Player players = 2;
}

message PresenceUpdateV1 {
  string status = 1;
  BasicPresenceType basicPresenceType = 2;
  string userDefinedPresence = 3;
  RichPresenceV1 richPresence = 4;
}

message PresenceV1 {
  string personaId = 1;
  string status = 2;
  string timestamp = 3;
  Player player = 4;
  BasicPresenceType basicPresenceType = 5;
  string userDefinedPresence = 6;
  RichPresenceV1 richPresence = 7;
  string sessionKey = 8;
  string clientVersion = 9;
  PlatformV1 platform = 10;
}

message PresenceUpdateErrorV1 {
  string errorCode = 1;
  string errorMessage = 2;
}

message PresenceSubscriptionErrorV1 {
  string personaId = 1;
  string errorCode = 2;
  string errorMessage = 3;
  Player player = 4;
}

message PresenceSubscriptionAllFriendsErrorV1 {
  string errorCode = 1;
  string errorMessage = 2;
}

message RichPresenceV1 {
  string game = 1;
  PlatformV1 platform = 2;
  string gameModeType = 3;
  string gameMode = 4;
  string gameSessionData = 5;
  RichPresenceType richPresenceType = 6;
  string startTimestamp = 7;
  string endTimestamp = 8;
  string customRichPresenceData = 9;
}