syntax = "proto3";

import "common.proto";

package antelope.rtm;

enum CommunicationType {
  NONE_COMMUNICATION_TYPE = 0;
  LOGIN_REQUEST = 1;
  LOGIN_RESPONSE = 2;
  PUBLISH_TEXT_REQUEST = 3;
  PUBLISH_BINARY_REQUEST = 4;
  PUBLISH_RESPONSE = 5;
  CHANNEL_MESSAGE = 6;
  SUBSCRIBE_REQUEST = 7;
  SUBSCRIBE_RESPONSE = 8;
  UNSUBSCRIBE_REQUEST = 9;
  UNSUBSCRIBE_RESPONSE = 10;
  HISTORY_REQUEST = 11;
  HISTORY_RESPONSE = 12;
  LOGOUT_REQUEST = 13;
}

enum ChannelMessageType {
  NONE_TEXT_MESSAGE = 0;
  TEXT_MESSAGE = 1;
  BINARY_MESSAGE = 2;
  GROUP_MEMBERSHIP_CHANGE = 3;
  CHAT_CONNECTED = 4;
  CHAT_DISCONNECTED = 5;
  CHAT_LEFT = 6;
  CUSTOM_MESSAGE = 7;
  CHAT_USER_MUTED = 8;
  CHAT_USER_UNMUTED = 9;
  CHANNEL_MEMBERSHIP_CHANGE = 10;
  STICKY_MESSAGE_CHANGED = 11;
  CHAT_TYPING_EVENT = 12;
  WORLD_CHAT_MEMBERSHIP_CHANGE = 13;
  GROUP_MEMBER_ATTRIBUTE_CHANGE = 14;
  GROUP_ATTRIBUTE_CHANGE = 15;
  GROUP_MEMBER_ROLE_CHANGE = 16;
}

enum GroupMembershipChangeType {
  NO_CHANGE = 0;
  LEAVE = 1;
  JOIN = 2;
  KICKED = 3;
}

enum MutedBy {
  NO_MUTE = 0;
  ADMIN = 1;
  USER = 2;
}

message Communication {
  oneof body {
    LoginRequest loginRequest = 2;
    LoginResponse loginResponse = 3;
    PublishTextRequest publishTextRequest = 4;
    PublishBinaryRequest publishBinaryRequest = 5;
    PublishResponse publishResponse = 6;
    ChannelMessage channelMessage = 7;
    SubscribeRequest subscribeRequest = 8;
    SubscribeResponse subscribeResponse = 9;
    UnsubscribeRequest unsubscribeRequest = 10;
    UnsubscribeResponse unsubscribeResponse = 11;
    HistoryRequest historyRequest = 12;
    HistoryResponse historyResponse = 13;
    LogoutRequest logoutRequest = 14;
  }
  Header header = 1;
}

message Header {
  CommunicationType type = 1;
  string requestId = 2;
}

message Player {
  string playerId = 1;
  string productId = 4;
}

message Channel {
  string channelId = 1;
  string channelName = 2;
  ea.antelope.ChannelType type = 3;
  bool crossGame = 4;
}

message ChannelMessage {
  oneof content {
    TextMessage textMessage = 5;
    BinaryMessage binaryMessage = 6;
    GroupMembershipChange membershipChange = 7;
    ea.antelope.ChatConnectedV1 chatConnected = 8;
    ea.antelope.ChatDisconnectedV1 chatDisconnected = 9;
    ea.antelope.ChatLeftV1 chatLeft = 10;
    ea.antelope.CustomMessage customMessage = 11;
    ea.antelope.ChatUserMutedV1 chatUserMuted = 12;
    ea.antelope.ChatUserUnmutedV1 chatUserUnmuted = 13;
    ea.antelope.ChannelMembershipChangeV1 channelMembershipChange = 14;
    ea.antelope.StickyMessageChangedV1 stickyMessageChanged = 15;
    ea.antelope.ChatTypingEventV1 chatTypingEvent = 16;
    ea.antelope.WorldChatMembershipChangeV1 worldChatMembershipChange = 17;
    ea.antelope.GroupMemberAttributeChangeV1 groupMemberAttributeChange = 18;
    ea.antelope.GroupAttributeChangeV1 groupAttributeChange = 19;
    ea.antelope.GroupMemberRoleChangeV1 groupMemberRoleChange = 20;
  }
  string messageId = 1;
  string channelId = 2;
  string timestamp = 3;
  ChannelMessageType type = 4;
}

message TextMessage {
  string fromPersonaId = 1;
  string fromDisplayName = 2;
  string text = 3;
  string originalText = 4;
  Player fromPlayer = 5;
  string fromNickName = 6;
  string fromPlatformDisplayName = 7;
  string fromPlatformNickName = 8;
  string metadata = 9;
  ea.antelope.MessageType messageType = 10;
  ea.antelope.StringId textMessageId = 11;
  ea.antelope.MessageContext messageContext = 12;
  repeated ea.antelope.ChatPropertyBagEntry chatPropertyBag = 13;
}

message BinaryMessage {
  string fromPersonaId = 1;
  string fromDisplayName = 2;
  bytes blob = 3;
  Player fromPlayer = 4;
  string fromNickName = 5;
  string fromPlatformDisplayName = 6;
  string fromPlatformNickName = 7;
  string metadata = 8;
}

message GroupMembershipChange {
  string targetPersonaId = 1;
  string targetDisplayName = 2;
  string initiatorPersonaId = 3;
  string initiatorDisplayName = 4;
  GroupMembershipChangeType type = 5;
  Player targetPlayer = 6;
  Player initiatingPLayer = 7;
  string targetNickName = 8;
  string initiatorNickName = 9;
  string targetAttributes = 10;
  string initiatorAttributes = 11;
}

message MutedUser {
  string personaId = 1;
  repeated MutedBy mutedBy = 2;
}

message ChannelMuteList {
  string channelId = 1;
  repeated MutedUser mutedUsers = 2;
}

message MutedUserV1 {
  string personaId = 1;
  repeated ea.antelope.MutedByV1 mutedBy = 2;
  Player player = 3;
}

message LoginRequest {
  string token = 1;
  bool reconnect = 2;
  bool heartbeat = 3;
}

message LogoutRequest {
}

message PublishTextRequest {
  string channelId = 1;
  string text = 2;
  ea.antelope.MessageType messageType = 3;
  int32 index = 4;
  string metadata = 5;
  ea.antelope.StringId textMessageId = 6;
  ea.antelope.MessageContext messageContext = 7;
  repeated ea.antelope.ChatPropertyBagEntry chatProperties = 8;
}

message PublishBinaryRequest {
  string channelId = 1;
  bytes blob = 2;
  string metadata = 3;
}

message SubscribeRequest {
  string channelId = 1;
}

message UnsubscribeRequest {
  string channelId = 1;
}

message HistoryRequest {
  string channelId = 1;
  string timestamp = 2;
  int32 recordCount = 3;
  string primaryFilterType = 4;
  string secondaryFilterType = 5;
}

message LoginResponse {
  bool success = 1;
  repeated Channel channels = 2;
  repeated ChannelMuteList muteList = 3;
  string errorCode = 4;
  string errorMessage = 5;
}

message PublishResponse {
  bool success = 1;
  string errorCode = 2;
  string errorMessage = 3;
  string messageId = 4;
  string timestamp = 5;
}

message SubscribeResponse {
  string channelId = 1;
  bool success = 2;
  string errorCode = 3;
  string errorMessage = 4;
  repeated MutedUserV1 mutedUsers = 5;
}

message UnsubscribeResponse {
  string channelId = 1;
  bool success = 2;
  string errorCode = 3;
  string errorMessage = 4;
}

message HistoryResponse {
  string channelId = 1;
  bool success = 2;
  repeated ChannelMessage messages = 3;
  string errorCode = 4;
  string errorMessage = 5;
}