query inGamePresenceData($offerIds: [String!]!, $locale: Locale = "en-us") {
    gameProducts(locale: $locale, offerIds: $offerIds) {
      items {
        id
        gameSlug
        baseItem(availabilities: [VISIBLE]) {
          id
          title
          shortDescription
          baseGameSlug
          gameType
          playableInPlatforms
          prereleaseGameType
          keyArt {
            title
            aspect1x1Image {
              path
              height
              width
            }
            aspect16x9Image {
              path
              height
              width
            }
          }
          primaryLogo {
            title
            largestImage {
              path
              height
              width
            }
          }
        }
      }
    }
  }
